#!/bin/bash
 
set -o errexit
set -o pipefail
set -o nounset

python3 /app/manage.py migrate
python3 /app/manage.py collectstatic --no-input

/usr/local/bin/gunicorn author_api.wsgi --bind 0.0.0.0:1981 --chdir=/app